[graph]
targets = []
all-features = true

[advisories]
version = 2
ignore = []

[licenses]
version = 2
allow = ["MIT"]
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
